import gradio as gr
import pandas as pd
import numpy as np
from numpy.linalg import norm
import torch
import os

from transformers import pipeline, AutoTokenizer, AutoModelForSeq2SeqLM
from sentence_transformers import SentenceTransformer
from langchain_ollama import OllamaLLM 
from langchain_core.prompts import PromptTemplate

# --- 1. Configuration & Initialization ---
MODEL_DIR = os.path.join("./models", "my_final_T5_qa_model") 
DATA_FILE = "amazon.csv"  
device = 0 if torch.cuda.is_available() else -1
device_name = "GPU" if device == 0 else "CPU"
print(f"Using device: {device_name}")

# Initialize local Agent LLM
try:
    agent_llm = OllamaLLM(model="llama3.1:latest") 
except Exception as e:
    print(f"Warning: Could not initialize Ollama. Error: {e}")
    agent_llm = None

# Initialize ASMP Embedder
print("Loading ASMP embedding model...")
try:
    embedder = SentenceTransformer('all-MiniLM-L6-v2', device=device_name.lower() if device_name == "CPU" else "cuda")
    print("✅ Embedder loaded.")
except Exception as e:
    print(f"❌ Error loading embedder: {e}")
    embedder = None

# Initialize Baseline T5
print("Loading fine-tuned T5 model and tokenizer...")
try:
    model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_DIR)
    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
    qa_pipeline = pipeline("text2text-generation", model=model, tokenizer=tokenizer, device=device)
    print("✅ T5 Pipeline loaded successfully.")
except Exception as e:
    print(f"❌ Error loading T5 model: {e}")
    qa_pipeline = None

# Load Data
print(f"Loading data from {DATA_FILE}...")
try:
    df = pd.read_csv(DATA_FILE)
    df.dropna(subset=['product_name', 'review_content'], inplace=True)
    
    # FIX 1: No more truncation! Load the full name. 
    # We will handle the display using CSS wrapping in the UI block.
    product_names = df['product_name'].unique().tolist()
    print(f"✅ Data loaded. Found {len(product_names)} unique products for search.")
except Exception as e:
    print(f"❌ Error loading data: {e}")
    df = None
    product_names = []

# --- 2. ASMP Mathematical Filter ---
def calculate_asmp(context_text, generated_text):
    if not embedder: return 0.0
    vec_c = embedder.encode(context_text)
    vec_g = embedder.encode(generated_text)
    
    mag_c = norm(vec_c)
    mag_g = norm(vec_g)
    
    if mag_c == 0 or mag_g == 0: return 0.0
    
    cos_sim = np.dot(vec_c, vec_g) / (mag_c * mag_g)
    cos_sim = np.clip(cos_sim, -1.0, 1.0) 
    
    angular_sim = 1 - (2 * np.arccos(cos_sim) / np.pi)
    mag_penalty = 1 - (abs(mag_g - mag_c) / max(mag_g, mag_c))
    
    asmp_score = angular_sim * mag_penalty
    return round(float(asmp_score), 4)

# --- 3. Define Agent Prompts ---
validator_template = """
You are a strict QA Verification Agent. Your job is to prevent AI hallucinations.
Read the user's question, the provided context (actual product reviews), and the Initial Answer generated by a baseline model.

Question: {question}
Review Context: {context}
Initial Answer to Verify: {initial_answer}

Task:
1. Does the Initial Answer contain factual information supported by the Review Context? 
2. If the answer contains information NOT found in the context, it is a hallucination.
3. DO NOT fail the answer for poor grammar, brevity, or if it only relies on a single review. ONLY issue a FAIL if the Initial Answer invents facts or explicitly contradicts the context.

Output Format:
Thought Process: [Your step-by-step reasoning]
Verdict: [PASS or FAIL]
Critique: [If FAIL, exactly what is wrong or hallucinated. If PASS, say "Accurate."]
"""
validator_prompt = PromptTemplate(template=validator_template, input_variables=["question", "context", "initial_answer"])

corrector_template = """
You are a Correction Agent. A previous model generated a flawed answer, and a Validator Agent has provided a critique.
Using ONLY the Review Context, generate a new, highly accurate, and concise answer to the user's question that fixes the issues raised in the critique.

Question: {question}
Review Context: {context}
Validator Critique: {critique}

Output the Corrected Answer only. Do not apologize or include preamble.
"""
corrector_prompt = PromptTemplate(template=corrector_template, input_variables=["question", "context", "critique"])

# --- 4. Core Logic Function ---
def answer_question_with_agents(selected_product_name, question):
    if qa_pipeline is None or df is None:
        return "Error loading system.", "N/A", "N/A", "N/A", "System Error"
    if not selected_product_name or not question:
        return "Please input data.", "N/A", "N/A", "N/A", "Input Error"
    
    try:
        # Search by the exact full name now
        product_reviews = df[df['product_name'] == selected_product_name]['review_content']
        
        if product_reviews.empty:
            return "No reviews found.", "0.0", "N/A", "N/A", "Error"
        
        context = " \n\n--- REVIEW --- \n\n ".join(product_reviews.tolist())[:3000] 
        
        prompt = f"question: {question} context: {context}"
        initial_answer = qa_pipeline(prompt, max_length=50, num_beams=4, early_stopping=True)[0]['generated_text']
        
        asmp_score = calculate_asmp(context, initial_answer)
        asmp_display = f"{asmp_score} / 1.00"
        
        if agent_llm is None:
            return initial_answer, asmp_display, "Ollama offline.", initial_answer, "No Agents"

        if asmp_score >= 0.65:
            return initial_answer, asmp_display, "Bypassed: ASMP >= 0.65 indicates high contextual grounding.", initial_answer, "Verified by Math (ASMP) 🧮"

        validation_chain = validator_prompt | agent_llm
        validation_result = validation_chain.invoke({
            "question": question, 
            "context": context, 
            "initial_answer": initial_answer
        })
        
        if "FAIL" in validation_result.upper():
            critique = validation_result.split("Critique:")[-1].strip() if "Critique:" in validation_result else validation_result
            correction_chain = corrector_prompt | agent_llm
            final_answer = correction_chain.invoke({
                "question": question,
                "context": context,
                "critique": critique
            })
            status = "Corrected by Dual-Agent Loop 🔄"
        else:
            final_answer = initial_answer
            status = "Verified by Agent (Pass) ✅"

        return initial_answer, asmp_display, validation_result, final_answer, status

    except Exception as e:
        print(f"Error during prediction: {e}")
        return "An error occurred.", "N/A", "N/A", "N/A", "Error"

# --- 5. UI Custom CSS & Gradio Build ---

# Custom CSS for the button color and dropdown wrapping
ui_css = """
#action-btn {
    background-color: #2563eb !important; /* Vibrant Blue */
    color: white !important;
    font-weight: bold !important;
    font-size: 16px !important;
    border: none !important;
}
#action-btn:hover {
    background-color: #1d4ed8 !important; /* Darker blue on hover */
}
/* Force dropdown text to wrap instead of trailing off */
.wrap-text .options li {
    white-space: normal !important;
    line-height: 1.3 !important;
    padding-top: 8px !important;
    padding-bottom: 8px !important;
    border-bottom: 1px solid #e5e7eb;
}
"""

print("Building Gradio interface...")
with gr.Blocks(title="ProductQA: Agentic Verification", css=ui_css) as demo:
    gr.Markdown("# 🤖 ProductQA: ASMP + Dual-Agent Verification Loop")
    gr.Markdown("Search for a product, ask a question, and observe the rigorous mathematical and agentic hallucination checks.")
    
    with gr.Row():
        product_input = gr.Dropdown(choices=product_names, label="Search Product Name", elem_classes="wrap-text")
        question_input = gr.Textbox(label="Your Question", placeholder="e.g., Is the charging cable durable?")
        
    submit_btn = gr.Button("Generate & Verify Answer", elem_id="action-btn")
    
    gr.Markdown("### 🔍 Verification Trace")
    with gr.Row():
        # Kept these two fixed since their output is always short
        initial_out = gr.Textbox(label="1. Base Model Answer (T5-Small)", interactive=False, lines=3, max_lines=3)
        asmp_out = gr.Textbox(label="2. ASMP Score (Threshold 0.65)", interactive=False, lines=3, max_lines=3)
        
    with gr.Row():
        # Removed max_lines: This box will now auto-expand to fit the full reasoning trace!
        agent_reasoning_out = gr.Textbox(label="3. Validator Agent's Logic", interactive=False, lines=3)
        
    with gr.Row():
        # Removed max_lines: These will also auto-expand as needed
        status_out = gr.Textbox(label="Verification Status", lines=1)
        final_out = gr.Textbox(label="4. Final Verified Answer", interactive=False, lines=2)

    submit_btn.click(
        fn=answer_question_with_agents,
        inputs=[product_input, question_input],
        outputs=[initial_out, asmp_out, agent_reasoning_out, final_out, status_out]
    )

if __name__ == "__main__":
    print("\n🚀 Launching GUI... Open the URL below in your browser.")
    demo.launch(theme=gr.themes.Soft())